### ISSUE TITLE
Plugin crashes QGIS on install

### ISSUE THREAD

**Issue by andrew-glos** [paulwithy/QGIS-OS-Address-Search#1]
QGIS crashes when the plugin is installed. If I restart QGIS, go to manage & install plugins, and tick the activate box, QGIS crashes again.
I've tried QGIS 3.10.11 and 3.16.1 as Citrix/AppV packages on Windows Server 2008, and 3.16.5 and 3.18.1 on Windows 10 (all 64-bit standalone installers).

Having had a poke about, it seems that it's the line
      startmarkers = [ i for i in iface.mapCanvas().scene().items() if issubclass(type(i), QgsVertexMarker)]
that's causing the crash.

If I start QGIS, open the Python Console, and type
      itemList = iface.mapCanvas().scene().items()
QGIS also crashes.

Google also found this issue at 3.10, supposedly fixed
https://github.com/qgis/QGIS/issues/32894

**Comment by paulwithy** [comment]
Thank you for the above information I've not seen this issue before. I have tried this on QGIS 3.16.4 on windows 10.0 and QGIS 3.12.1 on windows server 2012 R2 (6.3).

I can enter iface.mapCanvas().scene().items() into the console on both without a crash and the plugin works as expected.

**Comment by Adam-Gwent** [comment]
Hi Paul,

Can confirm that I'm experiencing same issue as @andrew-glos regarding QGIS crashing whilst installing, and whilst enabling/ticking the 'OS-Address Search' via plugin menu.

QGIS version 3.16.4 - Windows 10.

**Comment by paulwithy** [comment]
Hello Adam,

Please can you provide a screen shot of the QGIS about windows and confirm the version of windows your running.

![image](https://user-images.githubusercontent.com/25712217/120676137-a86bc500-c48d-11eb-8f21-0f013cf0fdbc.png)

**Comment by Adam-Gwent** [comment]
Hi Paul,

Thanks for replying so quickly!

Please find attached a screenshot of my QGIS details.

I'm on x64 bit windows - version: 10.0.19042

![QGIS_Version](https://user-images.githubusercontent.com/85304433/120681611-752c3480-c493-11eb-8a2f-2ace95f787b9.png)

**Comment by paulwithy** [comment]
Thanks Adam

I have installed all the plugins from your screen shot and I get an application crash.

The what3words was not in the QGIS plugin repo and the zip from the what3words website caused a crash every time I exit QGIS so I have removed that from my test.

Please will you try unticking the “Street View” plugin >> **exit QGIS** >> open QGIS >> tick the OS search for addresses plugin.

In my test I could reactivate the street view plugin but the OS search for addresses plugin would crash when you zoom to a result. It is possible we are trying to use the same resource. 

![image](https://user-images.githubusercontent.com/25712217/120690826-9d209580-c49d-11eb-9b15-ea55d2e84253.png)

**Comment by paulwithy** [comment]
As stated by @andrew-glos running "iface.mapCanvas().scene().items()" crashes QGIS. 

In my tests that only happens if the “Street View” plugin is enabled.

**Comment by andrew-glos** [comment]
Hi Paul,

Thanks for the update – I can confirm that the OS Address Search plugin runs fine when Street View is removed (I also had to remove “QGIS Resource Sharing”).

Attached is a modified version that handles markers differently, and which does run OK alongside the StreetView plugin.
Changes are marked with “Andrew”

I didn’t report it back before because we (Gloucestershire) run QGIS in a Citrix environment, and the modified OS Address Search was giving “Connection failed check proxy”.
My belief is that the proxy is OK (I can display the OS Maps API OK), but the actual proxy settings are locked down.
It works OK with QGIS running on the laptop rather than in a Citrix session (proxy also locked down).

It wasn’t terribly urgent for us because we have AddressBase for a 35 km buffer of the county, and normally use that.


Andrew
